language: cpp
compiler: gcc
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - libbz2-dev
      - libblas-dev
      - liblapack-dev
      - libarpack2-dev
      - libnetcdf-dev
      - netcdf-bin
      - clang
env:
    - COMPILER=gnu
    - COMPILER=clang
    - COMPILER=gnu OPENMP="-openmp" OPT=openmp

install:
    - ./configure $OPENMP $COMPILER
    - make -j2 install
      # Hack to get ambpdb installed with OpenMP
    - make -C src ambpdb && mv src/ambpdb bin/
script:
    - cd test && make test.showerrors
