os: Windows Server 2012

clone_folder: c:\projects\cpptraj

environment:
  matrix:
    - USE_CMAKE: "0"      
    - USE_CMAKE: "1"

install:
  - git submodule update --init --recursive
  - devtools\ci\appveyor\setup-environment.bat

build_script:
  - devtools\ci\appveyor\build.bat

after_build:
  - devtools\ci\appveyor\post-build.bat

test_script:
  - set CPPTRAJ_TEST_OS=windows
  - sh -lc "cd test; make test.showerrors"

artifacts:
  - path: cpptraj-$(APPVEYOR_BUILD_ID).zip
